language: python
sudo: false
python:
- '3.6'
before_script:
- if [ ${TRAVIS_PYTHON_VERSION} == '3.6' ]; then pip install flake8; flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics; fi
- "export DISPLAY=:99.0"  # https://docs.travis-ci.com/user/gui-and-headless-browsers
- sh -e /etc/init.d/xvfb start
- sleep 3
install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION pip pytest numpy pandas
  scipy matplotlib scikit-learn
- source activate testenv
- pip install python-coveralls
- pip install -r requirements.txt
- pip install -r optional-dependencies.txt
- python setup.py install
- cp nltools/tests/matplotlibrc .
script: coverage run --source nltools -m py.test
after_success:
- coveralls
